# Generated by Django 3.2.4 on 2021-06-18 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('precioMensual', models.CharField(max_length=40)),
                ('precioSemestral', models.CharField(max_length=40)),
                ('precioAnual', models.CharField(max_length=40)),
                ('activo', models.BooleanField()),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidoP', models.CharField(max_length=40)),
                ('apellidoM', models.CharField(max_length=40)),
                ('fechaNac', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=40)),
                ('ofertaSino', models.BooleanField()),
                ('activo', models.BooleanField()),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.deporte')),
            ],
        ),
    ]
