# Generated by Django 3.2.4 on 2021-06-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_deporte_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='apellidoM',
            new_name='materno',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='apellidoP',
        ),
        migrations.AddField(
            model_name='clientes',
            name='paterno',
            field=models.CharField(default=23, max_length=40, verbose_name='Apellido Paterno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='genero',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='rut',
            field=models.CharField(max_length=10, verbose_name='rut completo'),
        ),
    ]
